/**
 * Creative Director Agent
 *
 * Specialized agent for generating ideas, document structure,
 * and creative solutions. Helps with brainstorming and expansion.
 * Optimized for larger models like Devstral 24B for better creativity.
 */

import fs from 'fs/promises'
import {
  AgentType,
  AgentSettings
} from './types'
import { BaseAgent } from './base'
import { ToolDefinition } from '../types'
import { validateReadPath, isFile, isDirectory } from '../security'
import { agentEventBus } from './eventBus'
import { agentContextManager } from './contextManager'

// ============================================================================
// Types
// ============================================================================

/**
 * Creative idea generated by the agent.
 */
export interface CreativeIdea {
  title: string
  description: string
  rationale: string
}

/**
 * Parse ideas from creative agent response.
 */
export function parseIdeas(content: string): CreativeIdea[] {
  const ideas: CreativeIdea[] = []
  const regex = /<idea>([\s\S]*?)<\/idea>/g

  let match
  while ((match = regex.exec(content)) !== null) {
    const block = match[1]

    const titleMatch = block.match(/<title>([\s\S]*?)<\/title>/)
    const descMatch = block.match(/<description>([\s\S]*?)<\/description>/)
    const rationaleMatch = block.match(/<rationale>([\s\S]*?)<\/rationale>/)

    if (titleMatch && descMatch) {
      ideas.push({
        title: titleMatch[1].trim(),
        description: descMatch[1].trim(),
        rationale: rationaleMatch ? rationaleMatch[1].trim() : ''
      })
    }
  }

  return ideas
}

// ============================================================================
// Creative Agent
// ============================================================================

/**
 * Creative director agent for ideation and structure.
 */
export class CreativeAgent extends BaseAgent {
  readonly type: AgentType = 'creative'

  /** Workspace folders for path validation */
  private workspaceFolders: string[] = []

  constructor(
    settings: AgentSettings,
    workspaceFolders: string[] = []
  ) {
    super(settings, agentEventBus, agentContextManager)
    this.workspaceFolders = workspaceFolders
  }

  /**
   * Update workspace folders.
   */
  setWorkspaceFolders(folders: string[]): void {
    this.workspaceFolders = folders
  }

  /**
   * Get tool definitions for the creative agent.
   */
  getToolDefinitions(): ToolDefinition[] {
    return [
      {
        name: 'read_file',
        description: 'Read a file for context and inspiration.',
        parameters: {
          type: 'object',
          properties: {
            path: {
              type: 'string',
              description: 'Path to the file'
            }
          },
          required: ['path']
        }
      },
      {
        name: 'list_directory',
        description: 'List files to understand project structure.',
        parameters: {
          type: 'object',
          properties: {
            path: {
              type: 'string',
              description: 'Directory path'
            }
          },
          required: ['path']
        }
      },
      {
        name: 'search_files',
        description: 'Search for related content across files.',
        parameters: {
          type: 'object',
          properties: {
            query: {
              type: 'string',
              description: 'Text to search for'
            },
            path: {
              type: 'string',
              description: 'Directory to search in'
            }
          },
          required: ['query']
        }
      }
    ]
  }

  /**
   * Execute a tool call.
   */
  async executeTool(
    toolName: string,
    args: Record<string, unknown>
  ): Promise<{ success: boolean; result?: unknown; error?: string }> {
    switch (toolName) {
      case 'read_file':
        return this.executeReadFile(args)
      case 'list_directory':
        return this.executeListDirectory(args)
      case 'search_files':
        return this.executeSearchFiles(args)
      default:
        return { success: false, error: `Unknown tool: ${toolName}` }
    }
  }

  /**
   * Execute read file.
   */
  private async executeReadFile(
    args: Record<string, unknown>
  ): Promise<{ success: boolean; result?: unknown; error?: string }> {
    const filePath = String(args.path || '')

    if (!filePath) {
      return { success: false, error: 'Path is required' }
    }

    try {
      const validatedPath = validateReadPath(filePath, this.workspaceFolders)
      if (!isFile(validatedPath)) {
        return { success: false, error: `File not found: ${filePath}` }
      }

      let content = await fs.readFile(validatedPath, 'utf-8')

      // Truncate very long content
      const MAX_LENGTH = 8000
      if (content.length > MAX_LENGTH) {
        content = content.slice(0, MAX_LENGTH) + '\n... [truncated]'
      }

      return { success: true, result: content }
    } catch (error) {
      return { success: false, error: String(error) }
    }
  }

  /**
   * Execute list directory.
   */
  private async executeListDirectory(
    args: Record<string, unknown>
  ): Promise<{ success: boolean; result?: unknown; error?: string }> {
    const dirPath = String(args.path || '')

    if (!dirPath) {
      return { success: false, error: 'Path is required' }
    }

    try {
      const validatedPath = validateReadPath(dirPath, this.workspaceFolders)
      if (!isDirectory(validatedPath)) {
        return { success: false, error: `Directory not found: ${dirPath}` }
      }

      const entries = await fs.readdir(validatedPath, { withFileTypes: true })

      const result = entries
        .filter(e => !e.name.startsWith('.') && e.name !== 'node_modules')
        .map(e => ({
          name: e.name,
          type: e.isDirectory() ? 'directory' : 'file'
        }))

      return { success: true, result }
    } catch (error) {
      return { success: false, error: String(error) }
    }
  }

  /**
   * Execute search files.
   */
  private async executeSearchFiles(
    args: Record<string, unknown>
  ): Promise<{ success: boolean; result?: unknown; error?: string }> {
    const query = String(args.query || '')
    const searchPath = args.path
      ? String(args.path)
      : this.workspaceFolders[0]

    if (!query) {
      return { success: false, error: 'Query is required' }
    }

    if (!searchPath) {
      return { success: false, error: 'No workspace folder available' }
    }

    try {
      const validatedPath = validateReadPath(searchPath, this.workspaceFolders)
      const results = await this.searchInDir(validatedPath, query)
      return { success: true, result: results }
    } catch (error) {
      return { success: false, error: String(error) }
    }
  }

  /**
   * Search in directory for matching content.
   */
  private async searchInDir(
    dir: string,
    query: string
  ): Promise<Array<{ file: string; line: number; content: string }>> {
    const MAX_RESULTS = 30
    const results: Array<{ file: string; line: number; content: string }> = []
    const queryLower = query.toLowerCase()

    const search = async (currentDir: string) => {
      if (results.length >= MAX_RESULTS) return

      const entries = await fs.readdir(currentDir, { withFileTypes: true })

      for (const entry of entries) {
        if (results.length >= MAX_RESULTS) return

        if (entry.name.startsWith('.') || entry.name === 'node_modules') {
          continue
        }

        const fullPath = `${currentDir}/${entry.name}`

        if (entry.isDirectory()) {
          await search(fullPath)
        } else if (entry.name.endsWith('.md') || entry.name.endsWith('.txt')) {
          try {
            const content = await fs.readFile(fullPath, 'utf-8')
            const lines = content.split('\n')

            for (let i = 0; i < lines.length && results.length < MAX_RESULTS; i++) {
              if (lines[i].toLowerCase().includes(queryLower)) {
                results.push({
                  file: fullPath,
                  line: i + 1,
                  content: lines[i].trim().slice(0, 150)
                })
              }
            }
          } catch {
            // Skip files we can't read
          }
        }
      }
    }

    await search(dir)
    return results
  }

  /**
   * Generate ideas based on a topic or context.
   */
  async brainstorm(
    topic: string,
    context?: string,
    count: number = 5
  ): Promise<{ ideas: CreativeIdea[]; summary: string }> {
    if (!this.llmClient) {
      throw new Error('Agent not initialized')
    }

    // Build brainstorming prompt
    const prompt = `Generate ${count} creative ideas for the following topic:

Topic: ${topic}

${context ? `Context:\n${context}` : ''}

For each idea, provide:
<idea>
<title>Brief title</title>
<description>Detailed explanation</description>
<rationale>Why this works</rationale>
</idea>

Be specific and actionable. Consider multiple angles and approaches.`

    // Add to context
    this.contextManager.addMessage(this.type, {
      role: 'user',
      content: prompt
    })

    // Get LLM response
    const messages = this.contextManager.getMessagesForLLM(this.type)
    const response = await this.llmClient.chat(messages)

    // Parse ideas
    const ideas = parseIdeas(response.content)

    // Add response to context
    this.contextManager.addMessage(this.type, {
      role: 'assistant',
      content: response.content
    })

    return {
      ideas,
      summary: response.content
    }
  }

  /**
   * Generate a document outline.
   */
  async generateOutline(
    topic: string,
    requirements?: string
  ): Promise<string> {
    if (!this.llmClient) {
      throw new Error('Agent not initialized')
    }

    const prompt = `Create a detailed outline for a document about:

Topic: ${topic}

${requirements ? `Requirements:\n${requirements}` : ''}

Provide a hierarchical markdown outline with:
- Main sections (## headings)
- Subsections (### headings)
- Key points (bullet lists)
- Notes on what each section should cover`

    // Add to context
    this.contextManager.addMessage(this.type, {
      role: 'user',
      content: prompt
    })

    // Get LLM response
    const messages = this.contextManager.getMessagesForLLM(this.type)
    const response = await this.llmClient.chat(messages)

    // Add response to context
    this.contextManager.addMessage(this.type, {
      role: 'assistant',
      content: response.content
    })

    return response.content
  }
}

/**
 * Create a creative agent with the given settings.
 */
export function createCreativeAgent(
  settings: AgentSettings,
  workspaceFolders: string[] = []
): CreativeAgent {
  const agent = new CreativeAgent(settings, workspaceFolders)
  agent.initialize()
  return agent
}
